import 'dart:math' as math;
import 'dart:ui';

import 'package:flame/collisions.dart';
import 'package:flame/components.dart';

import '../../assets/sprites.dart';
import '../../game/game_state.dart';
import '../../game/hamster_game.dart';
import '../hamster/hamster.dart';

class ShockOrb extends PositionComponent
    with CollisionCallbacks, HasGameReference<HamsterGame> {
  ShockOrb({required Vector2 position, this.radius = 28})
    : super(position: position, size: Vector2.all(32), anchor: Anchor.center);

  final double radius;

  double _t = 0;

  static const PixelSprite _sprite = PixelSprite(
    width: 16,
    height: 16,
    pixels: [
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF000000,
      null,
      null,
      0xFF000000,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFF7C4DFF,
      0xFF000000,
      0xFF000000,
      0xFF7C4DFF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFF000000,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFF000000,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFF000000,
      0xFF000000,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFF000000,
      0xFF000000,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFF000000,
      0xFF000000,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFFFFFFF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF7C4DFF,
      0xFFB388FF,
      0xFFB388FF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF7C4DFF,
      0xFF7C4DFF,
      0xFF000000,
      0xFF000000,
      0xFF7C4DFF,
      0xFF7C4DFF,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0xFF000000,
      0xFF000000,
      null,
      null,
      0xFF000000,
      0xFF000000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  );

  @override
  Future<void> onLoad() async {
    await super.onLoad();
    size = game.hamster.size.clone();
    add(CircleHitbox());
  }

  @override
  void update(double dt) {
    super.update(dt);
    if (game.state != GameState.playing) return;

    _t += dt;

    // Orbit in a small circle, keeps the hitbox active.
    position.add(
      Vector2(math.cos(_t * 3) * radius * dt, math.sin(_t * 4) * radius * dt),
    );
  }

  @override
  void render(Canvas canvas) {
    _sprite.render(canvas, Rect.fromLTWH(0, 0, size.x, size.y));
  }

  @override
  void onCollisionStart(
    Set<Vector2> intersectionPoints,
    PositionComponent other,
  ) {
    super.onCollisionStart(intersectionPoints, other);

    if (other is! Hamster) return;

    // Always hurts; cannot be stomped.
    game.hitTrap();
  }
}
